server:
  port: 0
  error:
    include-binding-errors: always
    include-message: always 

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mauguer_dbproducto?serverTimezone=UTC
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect